// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKMQu_T2iln7VC2Rfrf926ywtuaikT0x8',
    appId: '1:341064436215:web:b3890485c3ddcf0b5146f2',
    messagingSenderId: '341064436215',
    projectId: 'bookstore-app-e4915',
    authDomain: 'bookstore-app-e4915.firebaseapp.com',
    storageBucket: 'bookstore-app-e4915.firebasestorage.app',
    measurementId: 'G-D93YSE7D90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7l8KKPRDKu2Do_DSVLkWPV6E7dYShg2Y',
    appId: '1:341064436215:android:e28cbe76684640e75146f2',
    messagingSenderId: '341064436215',
    projectId: 'bookstore-app-e4915',
    storageBucket: 'bookstore-app-e4915.firebasestorage.app',
  );
}
